apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: algn48/node-todo:37
        workingDir: /app
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: nodeapp-mysql-secret
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nodeapp-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodeapp-mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: nodeapp-mysql-secret
              key: MYSQL_DB
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
