---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysql-secret
spec:
  encryptedData:
    MYSQL_DATABASE: AgCh/SwKQr92bzgRPwf9QN4gIyyFqDjaeulBsxbQ9NZedeaRqv2jX4ndDjCpEHOREVKJD5AqjqPis1ic4fVepSTV46dcjubiqXsKxkXWtfDFc1j0y4sEDJrTY/zW2TifgbyGKLqipEr6HhnwV3/KMrl3VLTtHJFkjT4DmYEI1Je7/1xm1FlZ/WTABMF1sSis6mccus1REUA6hjFRQCO46ppOigQ0GnGAGOqjVY8/zH+4/FvsBlqK3NCQ6CrQvpXpjM1PesgQr8pfGiQ+5Ab+JRdI1sIfkanD90AWOdz1lGhlmlWDAsF6C/a7WrbyDS4UKvPmnJ6sFu2czH1YoxD2KMzEBIT9/6gwkPe8xmcaWuPJuEKEcuVVXxSjVcZldvittN1gQyOlkLj+4Mur83p2gDq3lH1CBBEmSDAsBr1gTFZ8ZInbxzrwqbcTDP5FoaiJiVkxF6X7JQaZvbxI/jMyEmFX99H64BgZI9cj84kcfHusJ0JIYcHjHAn5j9y5RfM3V/iXdXlBEwjRl0gXXfPlvF30v0k3DoDn8g34MBlMs/cm9UOWP92Y18jVQ9wYdMZLwKKVcu2F4JFe1gi3TG0exJOURWbLNOwq5HD4QFU1Ln9UKC/5sWHMj3TCFVNnEq7d4MaXMafymjcJL2+f5enCUXAo7sci1CagiRcd/vt6Kdwo5lRgUlgXAoGDb3SjOJ+O/dv2AY/cFw==
    MYSQL_ROOT_PASSWORD: AgCtWCP1q9shT4hI200pJkpGykefA69R6ytlNhfOzBX5XQ/0I5UAbr4c9cbaz+30+4RUhFKTtZw/9+cfIpZBTpFa59bOOkOCMGzH/o0c42jqh6lnNMJN5dsR7FBqcF82oEdnmX8A6Wa01ojFfCbQd812JjG0DA78GLyxffUt/fSqOvYOHzOB66bXpq5sYumaaYn26k1wKcYnw8qR+n4iu6RkqPuLz9pjM2wGOw0nicJu9Rdv5bYR3FqcFmgSK+CgGeR5qPf6G6btOMSLtmKTLC0U1jNMyIX2URADy1BQvH0paDGGqEoH2eZEihSwnBckzyUnhlScx8TA80FAnKdxagLYHuRfcRQ46ouTc9DzwdP8hj/d32jc0E535iZnDkooVDDXw8REV3bUVSNOx3AKFuiGtjuadI8wUiAf2ZtqiXt8gSSS0uJZ6upBlC9uozX3fAZvDox4Fxl/vUWmuULEAEm3x87dngiddaHBENtY+i+gZDFsZBByl0BEKzsjV8b13Xa9m/4udK+1BjBvt5Pie0ufhcgiX1/hjNpuIN6Lvgo5Up2VMiZxtoXM1Js2kQE4EzMgrq/+59w8b61Nn0gB7M9GPp2SGdfGWXHncxQeUG2SzBKbePCncuw4prG3b7iAKMTH0oMXKFKIe7hwirzUm8qkO1zDC1PtJBUvKB3X1GusoHX4X/qo6ajtLDMz8EYpi1HOEEA6hLw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysql-secret
