apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui #  https://henghelwanedu.webhook.office.com/webhookb2/10bc0db6-9570-4cd6-bd61-cf96071b37ed@85948b1d-6a8d-4b17-a25a-9b604bf64268/IncomingWebhook/bd5d622cc19b418ca50ab6afd37c95b8/fddb7f61-ffa8-42cc-8805-81d63cea5b40/V20DdS03za-UHeaK7TD-A8dSXf16hDHfYYPGXWlOpNwDY1  #
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
